# Generated by Django 5.1.7 on 2025-03-15 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
    ]
